language: python
python:
- '3.7'
- '2.7'
install:
- pip install -r requirements.txt
- pip install codecov
- python setup.py develop
script:
- python setup.py test
after_success:
- codecov
notifications:
  slack:
    secure: VwTYAI4jY7I8cr2qgOEnvNtVaNZT3uvQR3w+ASdzDExcxcDwNaFqVH9EfAabrvK3avmFiCQnEb37YXJDMcWVaTqrp+yaW+2C2gnDyBBuwmyc94IuEJhALuA7gxo53CHPx7I2vr87o9m8rMXOqS8eSnQhAzp1lnK9VZQXJq4E4ncefB9eKBgEnodsQMZycUdPrGoIP+urYZnGr3iE8m0UrTEwp3PZgTUlLdDCADWkLeSshwQX/Xn30chG1Rk1vxXm3JectzdjZM+DIOUp6S7npdMow4jnMxhdQuZkM566cePbhatcqHWko5A03PEcRpWrTixWZwgTzQ4oNdddg3Ixkz9a+y3bXiG+0gzSw56mf6Ezby2t2MyNh+bHJ3pIAZg7Na1kxkYQ4twqhrcZMG2MQooweH47sKQ2F6qbhARqx+u4FxKiTlWIQ5/9hAGkFEsmyZ6NFjniEGgvDeA5BBbFTdn/AlWKVlsd4ruqJLZckVVtj5ghGjdaB9tyBeiBwNW2+eAMIBzLHn8PmS+zrd3hT+socEblFOQLEJNwAJQtbXHnwJLGPG6yTmMIwJ/57GZkqMEiGRl5WhlzpJivn37mla7rQ5Z2wLvs2ZL8cchNcfNx2kiv2MwDcMul1/LEWkd1IcRugR2S2VxTrE4tUIaPSf3ShkB9F2R4PPe7tbYxnDM=
